apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "logstash.fullname" . }}-config
  labels:
    {{- include "logstash.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.logstashConfig }}
  {{ $key }}: |
{{ $value | indent 4 }}
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "logstash.fullname" . }}-pipeline
  labels:
    {{- include "logstash.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.logstashPipeline }}
  {{ $key }}: |
{{ $value | indent 4 }}
  {{- end }}