version: '3'
services:
  config-server-app:
    image: config-server-app:latest
    build:
      context: .
      dockerfile: config-server/Dockerfile
    environment:
      SPRING_CLOUD_ZOOKEEPER_CONNECT_STRING: zookeeper:2181
    ports:
      - "8888:8888"
    depends_on:
      - zookeeper
    networks:
      - app_network

  service-a-app:
    image: service-a-app:latest
    build:
      context: .
      dockerfile: service-a/Dockerfile
    environment:
      CONFIG_SERVER_URL: http://config-server-app:8888
      SPRING_CLOUD_ZOOKEEPER_CONNECT_STRING: zookeeper:2181
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://keycloak:8080/realms/bankapp/protocol/openid-connect/certs
    ports:
      - "8081:8081"
    depends_on:
      - zookeeper
      - config-server-app
    restart: on-failure
    networks:
      - app_network

  service-b-app:
    image: service-b-app:latest
    build:
      context: .
      dockerfile: service-b/Dockerfile
    environment:
      CONFIG_SERVER_URL: http://config-server-app:8888
      SPRING_CLOUD_ZOOKEEPER_CONNECT_STRING: zookeeper:2181
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://keycloak:8080/realms/bankapp/protocol/openid-connect/certs
    ports:
      - "8082:8082"
    depends_on:
      - zookeeper
      - config-server-app
    restart: on-failure
    networks:
      - app_network

  service-front-app:
    image: service-front-app:latest
    build:
      context: .
      dockerfile: service-front/Dockerfile
    environment:
      CONFIG_SERVER_URL: http://config-server-app:8888
      SPRING_CLOUD_ZOOKEEPER_CONNECT_STRING: zookeeper:2181
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://keycloak:8080/realms/bankapp/protocol/openid-connect/certs
    ports:
      - "8083:8083"
    depends_on:
      - zookeeper
      - config-server-app
    restart: on-failure
    networks:
      - app_network

  service-gateway-app:
    image: service-gateway-app:latest
    build:
      context: .
      dockerfile: service-gateway/Dockerfile
    environment:
      CONFIG_SERVER_URL: http://config-server-app:8888
      SPRING_CLOUD_ZOOKEEPER_CONNECT_STRING: zookeeper:2181
      SPRING_R2DBC_URL: r2dbc:postgresql://gateway-postgres:5432/gateway-db
      SPRING_R2DBC_USERNAME: postgres
      SPRING_R2DBC_PASSWORD: postgres
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_AUTHORIZATION_URI: http://keycloak:8080/realms/bankapp/protocol/openid-connect/auth
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_TOKEN_URI: http://keycloak:8080/realms/bankapp/protocol/openid-connect/token
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_JWK_SET_URI: http://keycloak:8080/realms/bankapp/protocol/openid-connect/certs
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_BANKAPP_CLIENT_CLIENT_ID: bankapp-client
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_BANKAPP_CLIENT_CLIENT_SECRET: VmGXQDXNGOZzJH5Mx7Fi4OyHtnb3IH8A
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_BANKAPP_CLIENT_PROVIDER: keycloak
    ports:
      - "8080:8080"
    depends_on:
      - zookeeper
      - config-server-app
      - service-a-app
      - service-b-app
      - service-front-app
      - gateway-postgres
      - keycloak
    restart: on-failure
    networks:
      - app_network

  gateway-postgres:
    image: postgres:16.1-alpine
    environment:
      POSTGRES_DB: gateway-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - app_network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    tmpfs: "/datalog"
    ports:
      - "22181:2181"
    networks:
      - app_network

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.3
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8180:8080"
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json
    command: start-dev --import-realm
    networks:
      - app_network

networks:
  app_network: