version: '3'
services:

  # -------- Infrastructure -------- #
  config-server-app:
    image: config-server-app:latest
    build:
      context: .
      dockerfile: config-server/Dockerfile
    environment:
      SPRING_CLOUD_ZOOKEEPER_CONNECT_STRING: zookeeper:2181
    ports:
      - "8888:8888"
    depends_on:
      - zookeeper
    networks:
      - app_network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    tmpfs: "/datalog"
    ports:
      - "22181:2181"
    networks:
      - app_network

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.3
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8180:8080"
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json
    command: start-dev --import-realm
    networks:
      - app_network

  # -------- Databases -------- #
  accounts-postgres:
    image: postgres:16.1-alpine
    environment:
      POSTGRES_DB: accounts-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - app_network

  exchange-postgres:
    image: postgres:16.1-alpine
    environment:
      POSTGRES_DB: exchange-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    networks:
      - app_network

  notifications-postgres:
    image: postgres:16.1-alpine
    environment:
      POSTGRES_DB: notifications-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    networks:
      - app_network

networks:
  app_network: