keycloak:
  image:
    repository: quay.io/keycloak/keycloak
    tag: "26.1.3"
    pullPolicy: IfNotPresent
  
  # Admin credentials
  admin:
    username: admin
    password: admin
  
  # Database configuration disabled for development mode
  # Keycloak will use in-memory H2 database in start-dev mode
  database:
    vendor: ""  # Empty to disable database configuration
  
  # Keycloak configuration
  hostname: localhost
  hostnamePort: 8080
  
  # Resource configuration
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi
  
  # Persistence for Keycloak data
  persistence:
    enabled: false
    storageClass: ""
    size: 1Gi
  
  # Realm import configuration
  realmImport:
    enabled: true
    # The realm export file will be mounted as a ConfigMap

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: keycloak.bankapp.local
      paths:
        - path: /
          pathType: Prefix
  tls: []