spring:
  application:
    name: service-front

  # Config Server
  config:
    import: configserver:${CONFIG_SERVER_URL:http://127.0.0.1:8888}

  # Cloud
  cloud:
    # Zookeeper
    zookeeper:
      discovery:
        enabled: true
      connect-string: localhost:2181

  # Security
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8180/realms/bankapp/protocol/openid-connect/certs

  # Thymeleaf
  thymeleaf:
    encoding: UTF-8
    mode: HTML

logging:
  level:
    web: debug