server:
  port: 8085

spring:

  # Service Discovery
  application:
    name: service-exchange

  main:
    allow-bean-definition-overriding: true # убрать после dev

  # Cloud
  cloud:

  # Security
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8180/realms/bankapp/protocol/openid-connect/certs

  # Liquibase
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
    drop-first: true

  # Datasource (reactive)
  r2dbc:
    url: r2dbc:postgresql://localhost:5433/exchange-db
    username: postgres
    password: postgres

headers:
  user-header: X-User-Login

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

logging:
  level:
    web: info
    org.springframework.security: info

services:
  service-gateway:
    name: "localhost:8080"