server:
  port: 8083

spring:

  # Service Discovery
  application:
    name: service-blocker

  main:
    allow-bean-definition-overriding: true # убрать после dev

  # Cloud
  cloud:

  # Security
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8180/realms/bankapp/protocol/openid-connect/certs

headers:
  user-header: X-User-Login

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

logging:
  level:
    web: info
    org.springframework.security: info

services:
  service-gateway:
    name: "localhost:8080"