spring:
  application:
    name: service-gateway
  main:
    allow-bean-definition-overriding: true # убрать после dev

  # Config Server
  config:
    import: configserver:${CONFIG_SERVER_URL:http://127.0.0.1:8888}

  # Cloud
  cloud:
    # Zookeeper
    zookeeper:
      discovery:
        enabled: true
      connect-string: localhost:2181

    # Gateway (service-locator)
    gateway:
      server:
        webflux:
          routes:
            - id: edit-password-route
              uri: lb://service-accounts
              predicates:
                - Path=/user/{login}/editPassword
              filters:
                - TokenRelay=bankapp-client

            - id: exchange-route
              uri: lb://service-exchange
              predicates:
                - Path=/api/rates
              filters:
                - TokenRelay=bankapp-client

            - id: edit-accounts-route
              uri: lb://service-accounts
              predicates:
                - Path=/user/{login}/editUserAccounts
              filters:
                - TokenRelay=bankapp-client

            - id: cash-route
              uri: lb://service-cash
              predicates:
                - Path=/user/{login}/cash
              filters:
                - TokenRelay=bankapp-client

            - id: notifications-route
              uri: lb://service-notifications
              predicates:
                - Path=/api/{login}/notifications
              filters:
                - TokenRelay=bankapp-client

            - id: transfer-route
              uri: lb://service-transfer
              predicates:
                - Path=/user/{login}/transfer
              filters:
                - TokenRelay=bankapp-client

            # API Controllers
#
#            - id: blocker-route
#              uri: lb://service-blocker
#              predicates:
#                - Path=/api/{time}/block
#              filters:
#                - TokenRelay=bankapp-client
#
#            - id: cash-balance-route
#              uri: lb://service-accounts
#              predicates:
#                - Path=/api/{login}/cash
#              filters:
#                - TokenRelay=bankapp-client
#
#            - id: notifications-user-route
#              uri: lb://service-notifications
#              predicates:
#                - Path=/api/{login}/notifications
#              filters:
#                - TokenRelay=bankapp-client

  # Security
  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: http://localhost:8180/realms/bankapp/protocol/openid-connect/token
            authorization-uri: http://localhost:8180/realms/bankapp/protocol/openid-connect/auth
            jwk-set-uri: http://localhost:8180/realms/bankapp/protocol/openid-connect/certs
        registration:
          bankapp-client:
            client-id: bankapp-client
            client-secret: VmGXQDXNGOZzJH5Mx7Fi4OyHtnb3IH8A
            authorization-grant-type: client_credentials
            scope: openid
            provider: keycloak

  # Thymeleaf
  thymeleaf:
    encoding: UTF-8
    mode: HTML

# Logging
logging:
  level:
    web: trace
    org.springframework.security: trace