spring:
  application:
    name: service-gateway

  # Config Server
  config:
    import: configserver:${CONFIG_SERVER_URL:http://127.0.0.1:8888}

  # Cloud
  cloud:
    # Zookeeper
    zookeeper:
      discovery:
        enabled: true
      connect-string: localhost:2181
    # Gateway
    gateway:
      server:
        webmvc:
          routes:
            - id: service-a-route
              uri: lb://service-a
              predicates:
                - Path=/service-a/**
              filters:
                - RewritePath=/service-a/?(?<segment>.*), /$\{segment}
            - id: service-b-route
              uri: lb://service-b
              predicates:
                - Path=/service-b/**
              filters:
                - RewritePath=/service-b/?(?<segment>.*), /$\{segment}

logging:
  level:
    web: debug