host: 127.0.0.1
base-url: http://${host}

services:
  service-a:
    host: ${host}
    port: 8081
    url: ${base-url}:${services.service-a.port}
  service-b:
    host: ${host}
    port: 8082
    url: ${base-url}:${services.service-b.port}
  service-gateway:
    host: ${host}
    port: 8080
    url: ${base-url}:${services.service-gateway.port}
  config-server:
    host: ${host}
    port: 8888
    url: ${base-url}:${services.config-server.port}