host: 127.0.0.1
base-url: http://${host}

services:
  service-gateway:
    host: ${host}
    port: 8080
    url: ${base-url}:${services.service-gateway.port}
  config-server:
    host: ${host}
    port: 8888
    url: ${base-url}:${services.config-server.port}
  service-blocker:
    host: ${host}
    port: 8083
    url: ${base-url}:${services.service-blocker.port}
  service-accounts:
    host: ${host}
    port: 8084
    url: ${base-url}:${services.service-accounts.port}
  service-exchange:
    host: ${host}
    port: 8085
    url: ${base-url}:${services.service-exchange.port}
  service-cash:
    host: ${host}
    port: 8086
    url: ${base-url}:${services.service-cash.port}
  service-notifications:
    host: ${host}
    port: 8087
    url: ${base-url}:${services.service-notifications.port}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always