server:
  port: ${services.service-front.port}

spring:
  main:
    allow-bean-definition-overriding: true # убрать после dev

  # Cloud
  cloud:
    # Zookeeper
    zookeeper:
      discovery:
        enabled: true
      connect-string: localhost:2181

  # Security
  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: http://localhost:8180/realms/bankapp/protocol/openid-connect/token
            authorization-uri: http://localhost:8180/realms/bankapp/protocol/openid-connect/auth
            jwk-set-uri: http://localhost:8180/realms/bankapp/protocol/openid-connect/certs
        registration:
          bankapp-client:
            client-id: bankapp-client
            client-secret: VmGXQDXNGOZzJH5Mx7Fi4OyHtnb3IH8A
            authorization-grant-type: client_credentials
            scope: openid
            provider: keycloak

  # Thymeleaf
  thymeleaf:
    encoding: UTF-8
    mode: HTML