apiVersion: v2
name: bankapp
description: BankApp umbrella chart

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  # Infrastructure Dependencies
  - name: keycloak
    version: "0.1.0"
    repository: "file://../charts/keycloak"
    condition: keycloak.enabled
  
  - name: postgresql-accounts
    version: "0.1.0"
    repository: "file://../charts/postgresql-accounts"
    condition: postgresql-accounts.enabled
  
  - name: postgresql-exchange
    version: "0.1.0"
    repository: "file://../charts/postgresql-exchange"
    condition: postgresql-exchange.enabled
  
  - name: postgresql-notifications
    version: "0.1.0"
    repository: "file://../charts/postgresql-notifications"
    condition: postgresql-notifications.enabled

  # Service Dependencies
  - name: service-gateway
    version: "0.1.0"
    repository: "file://../charts/service-gateway"
    condition: service-gateway.enabled
  
  - name: service-front
    version: "0.1.0"
    repository: "file://../charts/service-front"
    condition: service-front.enabled
  
  - name: service-accounts
    version: "0.1.0"
    repository: "file://../charts/service-accounts"
    condition: service-accounts.enabled
  
  - name: service-cash
    version: "0.1.0"
    repository: "file://../charts/service-cash"
    condition: service-cash.enabled
  
  - name: service-convert
    version: "0.1.0"
    repository: "file://../charts/service-convert"
    condition: service-convert.enabled
  
  - name: service-exchange
    version: "0.1.0"
    repository: "file://../charts/service-exchange"
    condition: service-exchange.enabled
  
  - name: service-transfer
    version: "0.1.0"
    repository: "file://../charts/service-transfer"
    condition: service-transfer.enabled
  
  - name: service-blocker
    version: "0.1.0"
    repository: "file://../charts/service-blocker"
    condition: service-blocker.enabled
  
  - name: service-notifications
    version: "0.1.0"
    repository: "file://../charts/service-notifications"
    condition: service-notifications.enabled