server:
  port: 8086

spring:

  # Service Discovery
  application:
    name: service-cash

  main:
    allow-bean-definition-overriding: true # убрать после dev

  # Cloud
  cloud:

    # Gateway (service-locator)
    gateway:
      server:
        webflux:
          routes:
            - id: service-front-route
              uri: http://bankapp-service-gateway:8080
              predicates:
                - Path=/
              filters:
                - TokenRelay=bankapp-client

  # Security
  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: http://localhost:8180/realms/bankapp/protocol/openid-connect/token
            authorization-uri: http://localhost:8180/realms/bankapp/protocol/openid-connect/auth
            jwk-set-uri: http://localhost:8180/realms/bankapp/protocol/openid-connect/certs
        registration:
          bankapp-client:
            client-id: bankapp-client
            client-secret: VmGXQDXNGOZzJH5Mx7Fi4OyHtnb3IH8A
            authorization-grant-type: client_credentials
            scope: openid
            provider: keycloak

# Circuit Breaker
resilience4j:
  retry:
    instances:
      gateway-service:
        max-attempts: 3
        wait-duration: 1s
  circuitbreaker:
    instances:
      gateway-service:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s

headers:
  user-header: X-User-Login

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

logging:
  level:
    web: info
    org.springframework.security: info

services:
  service-gateway:
    name: "bankapp-service-gateway:8080"