spring:
  application:
    name: service-cash
  main:
    allow-bean-definition-overriding: true # убрать после dev

  # Config Server
  config:
    import: configserver:${CONFIG_SERVER_URL:http://127.0.0.1:8888}

  # Cloud
  cloud:
    # Zookeeper
    zookeeper:
      discovery:
        enabled: true
      connect-string: localhost:2181

    # Gateway (service-locator)
    gateway:
      server:
        webflux:
          routes:
            - id: service-front-route
              uri: lb://service-gateway
              predicates:
                - Path=/
              filters:
                - TokenRelay=bankapp-client

  # Security
  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: http://localhost:8180/realms/bankapp/protocol/openid-connect/token
            authorization-uri: http://localhost:8180/realms/bankapp/protocol/openid-connect/auth
            jwk-set-uri: http://localhost:8180/realms/bankapp/protocol/openid-connect/certs
        registration:
          bankapp-client:
            client-id: bankapp-client
            client-secret: VmGXQDXNGOZzJH5Mx7Fi4OyHtnb3IH8A
            authorization-grant-type: client_credentials
            scope: openid
            provider: keycloak

# Logging
logging:
  level:
    web: trace
    org.springframework.security: trace